info:
  description: "OMS gateway"

spring:
  application:
    name: api-gateway

security:
  basic:
    enabled: false
#zuul.routes.customerproxy.path=/customer/*
#zuul.routes.customerproxy.serviceId=CUSTOMERSERVICE
#zuul.routes.customerproxy.stripPrefix=false


logging:
  level:
    root: DEBUG
    org.springframework.web: ERROR
    com.oms.apigateway: DEBUG

zuul:
  routes:
    customerproxy:
      path: /customer/*
      serviceId: customer-service
      stripPrefix: false



