info:
  description: "OMS gateway"

spring:
  application:
    name: api-gateway

security:
  basic:
    enabled: false

logging:
  level:
    root: DEBUG
    org.springframework.web: ERROR
    com.oms.apigateway: DEBUG

zuul:
  routes:
    customerproxy:
      path: /customer/*
      serviceId: play-customer-service
      stripPrefix: false



