info:
  description: "OMS gateway"

spring:
  application:
    name: api-gateway

security:
  basic:
    enabled: false

logging:
  level:
    root: DEBUG
    org.springframework.web: ERROR
    com.oms.apigateway: DEBUG

zuul:
  ignoredPatterns: /api, /swagger-ui.html, /actuator/**, /configuration/**, /webjars/**, /swagger-resources/**, /swagger-composite/**, /v2/**, /jv/redirect/**, /heartbeat, /gateway/**, /favicon.ico, /public ,/login
  routes:
    inventoryproxy:
      path: /inventory/**
#      url: https://play-inventory-service.local.pcfdev.io
      serviceId: play-inventory-service
      stripPrefix: false

    customerproxy:
      path: /customer/*
#      url: https://customer-service.local.pcfdev.io
      serviceId: customer-service
      stripPrefix: false
    inventoryproxy:
      path: /inventory/*
#      url: https://inventory-service.local.pcfdev.io
      serviceId: inventory-service
      stripPrefix: false





