info:
  description: "OMS gateway"

spring:
  application:
    name: api-gateway

security:
  basic:
    enabled: false

logging:
  level:
    root: DEBUG
    org.springframework.web: ERROR
    com.oms.apigateway: DEBUG

zuul:
  prefix: /api
  ignoredPatterns: /api, /swagger-ui.html, /actuator/**, /configuration/**, /webjars/**, /swagger-resources/**, /swagger-composite/**, /v2/**, /jv/redirect/**, /heartbeat, /gateway/**, /favicon.ico, /public ,/login
  routes:
    customerproxy:
      path: /customer/**
#      url: https://customer-service.local.pcfdev.io
      serviceId: customer-service
      stripPrefix: false
    inventoryproxy:
      path: /inventory/**
      serviceId: inventory-service
      stripPrefix: false
    productproxy:
      path: /product/**
      serviceId: product-service
      stripPrefix: false
    eventproxy:
      path: /event/**
      serviceId: event-service
      stripPrefix: false
    mailproxy:
      path: /mail/**
      serviceId: mail-service
      stripPrefix: false
    orderproxy:
      path: /order/**
      serviceId: order-comp-service
      stripPrefix: false










