info:
  description: "OMS gateway"

spring:
  application:
    name: api-gateway

security:
  basic:
    enabled: false

logging:
  level:
    root: DEBUG
    org.springframework.web: ERROR
    com.oms.apigateway: DEBUG

zuul:
  routes:
    inventoryproxy:
      path: /inventory/*
      url: https://play-inventory-service.local.pcfdev.io
      serviceId: play-inventory-service
      stripPrefix: false



